---
- name: Configure Base System Settings
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Install EPEL repository
      dnf:
        name: epel-release
        state: present

    - name: Install required packages
      dnf:
        name:
          - vim
          - cockpit
          - net-tools
          - python3-pip
          - python3-setuptools
          - wget
          - curl
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
          - nfs-utils
          - iproute-tc
        state: present

    - name: Disable SELinux
      block:
        - name: Set SELinux to disabled state
          selinux:
            state: disabled
          
        - name: Ensure SELinux is disabled at boot
          lineinfile:
            path: /etc/selinux/config
            regexp: '^SELINUX='
            line: 'SELINUX=disabled'

    - name: Enable and start Cockpit service
      systemd:
        name: cockpit.socket
        state: started
        enabled: true

    - name: Add Kubernetes repository
      yum_repository:
        name: kubernetes
        description: Kubernetes repository
        baseurl: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/
        gpgcheck: true
        gpgkey: https://pkgs.k8s.io/core:/stable:/v1.31/rpm/repodata/repomd.xml.key
        enabled: true

    - name: Configure containerd
      block:
        - name: Add containerd repository
          get_url:
            url: https://download.docker.com/linux/centos/docker-ce.repo
            dest: /etc/yum.repos.d/docker-ce.repo

        - name: Install containerd
          dnf:
            name: containerd.io
            state: present

        - name: Create containerd config directory
          file:
            path: /etc/containerd
            state: directory
            mode: '0755'

        - name: Generate default containerd config
          command: containerd config default
          register: containerd_config
          changed_when: false

        - name: Write containerd config
          copy:
            content: "{{ containerd_config.stdout }}"
            dest: /etc/containerd/config.toml
            owner: root
            group: root
            mode: '0644'

        - name: Restart containerd
          systemd:
            name: containerd
            state: restarted
            enabled: true

    - name: Configure system for Kubernetes
      block:
        - name: Disable swap
          command: swapoff -a
          when: ansible_swaptotal_mb > 0

        - name: Remove swap from fstab
          replace:
            path: /etc/fstab
            regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
            replace: '# \1'

        - name: Ensure br_netfilter module is loaded
          modprobe:
            name: br_netfilter
            state: present

        - name: Ensure overlay module is loaded
          modprobe:
            name: overlay
            state: present

        - name: Persist module loading
          copy:
            dest: /etc/modules-load.d/k8s.conf
            content: |
              overlay
              br_netfilter
            mode: '0644'

        - name: Configure kernel parameters for Kubernetes
          sysctl:
            name: "{{ item.name }}"
            value: "{{ item.value }}"
            state: present
            sysctl_set: true
            reload: true
          loop:
            - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
            - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
            - { name: 'net.ipv4.ip_forward', value: '1' }

    - name: Configure firewall
      block:
        - name: Install firewalld
          dnf:
            name: firewalld
            state: present

        - name: Start and enable firewalld
          systemd:
            name: firewalld
            state: started
            enabled: true

        - name: Configure required ports for Kubernetes
          firewalld:
            port: "{{ item }}"
            permanent: true
            state: enabled
          loop:
            - 6443/tcp    # Kubernetes API server
            - 2379-2380/tcp # etcd server client API
            - 10250/tcp   # Kubelet API
            - 10251/tcp   # kube-scheduler
            - 10252/tcp   # kube-controller-manager
            - 8472/udp    # Calico VXLAN
            - 179/tcp     # Calico BGP
            
        - name: Reload firewalld
          systemd:
            name: firewalld
            state: reloaded