---
# Kubernetes Configuration
kubernetes_version: "1.31.3"
pod_network_cidr: "192.168.0.0/16"
service_cidr: "10.96.0.0/12"

# CNI Configuration
cni_plugin: "calico"
calico_version: "v3.29.1"

# Load Balancer Configuration
metallb_version: "v0.14.8"
metallb_ip_range: "192.168.1.240-192.168.1.250"

# Ingress Configuration
nginx_ingress_version: "v1.11.3"

# Container Runtime
container_runtime: "containerd"
containerd_version: "1.7.24"